environment:
  psg_api_key:
    secure: zCMMo4h9MrdM9+jbF+fvWIVFIlw5KkcjZSX0WLQHwH07qNK6PE6BvdPcoch88gE/
  
build: off

test_script:
- ps: $ErrorActionPreference = "Stop"
- ps: Get-PSRepository
- ps: Find-Module AppVeyorTestPsGallery
- ps: (Get-Content .\AppVeyorTestPsGallery\AppVeyorTestPsGallery.psd1).replace('<BUILD_VERSION>', $env:APPVEYOR_BUILD_VERSION) | Set-Content .\AppVeyorTestPsGallery\AppVeyorTestPsGallery.psd1
- ps: mkdir $env:userprofile\Documents\WindowsPowerShell\Modules\AppVeyorTestPsGallery
- ps: Copy-Item .\AppVeyorTestPsGallery\* $env:userprofile\Documents\WindowsPowerShell\Modules\AppVeyorTestPsGallery\ -Recurse -Force
- ps: Publish-Module -Name AppVeyorTestPsGallery -NuGetApiKey $env:psg_api_key
- ps: Remove-Item $env:userprofile\Documents\WindowsPowerShell\Modules\AppVeyorTestPsGallery -Recurse -Force
- ps: Write-Host "Wait for 30 seconds until the module is published"; Start-Sleep -s 30
- ps: Find-Module AppVeyorTestPsGallery
- ps: Install-Module AppVeyorTestPsGallery -Scope AllUsers
- ps: Get-PackageProvider
- ps: Get-Module
- ps: dir $env:ProgramFiles\WindowsPowerShell\Modules\AppVeyorTestPsGallery\$env:APPVEYOR_BUILD_VERSION
